Repository silverstripe/silverstripe-fulltextsearch, pull requests merged in 2018-03, with the labels that each got.

#202 NEW Add SearchVariant::withCommon to run callbacks on relevant variants rather than all
  src/Search/Variants/SearchVariant.php
  src/Solr/SolrIndex.php
  tests/SolrIndexTest.php
Labels: affects/v4

#206 Fix issue where schema.xml etc is put in a different dir than the cor…
  src/Solr/Services/SolrService.php
  src/Solr/SolrIndex.php
  tests/SolrIndexTest.php
Labels: affects/v4, change/major, effort/medium, impact/critical, type/bug

#207 FIX Reenable indexing of relationship fields
  src/Search/Indexes/SearchIndex.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#208 NEW Update to use proxied DB instead of self-proxied
  .scrutinizer.yml
  _config/database.yml
  composer.json
  src/Search/Captures/SearchManipulateCapture_MySQLDatabase.php
  src/Search/Captures/SearchManipulateCapture_PostgreSQLDatabase.php
  src/Search/Captures/SearchManipulateCapture_SQLite3Database.php
  src/Search/Extensions/ProxyDBExtension.php
  src/Search/Updaters/SearchUpdater.php
Labels: affects/v4, change/minor

#210 NEW Allow autoconfigure to be disabled via configuration
  docs/en/index.md
  src/Search/Updaters/SearchUpdater.php
Labels: affects/v4, change/minor
